/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as KbRouteImport } from './routes/kb'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechStackIndexRouteImport } from './routes/tech-stack/index'
import { Route as ServiceIndexRouteImport } from './routes/service/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as TechStackTechIdRouteImport } from './routes/tech-stack/$techId'
import { Route as ServiceServiceIdRouteImport } from './routes/service/$serviceId'
import { Route as PortfolioProjectIdRouteImport } from './routes/portfolio/$projectId'
import { Route as BlogBlogIdRouteImport } from './routes/blog/$blogId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const KbRoute = KbRouteImport.update({
  id: '/kb',
  path: '/kb',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechStackIndexRoute = TechStackIndexRouteImport.update({
  id: '/tech-stack/',
  path: '/tech-stack/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceIndexRoute = ServiceIndexRouteImport.update({
  id: '/service/',
  path: '/service/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechStackTechIdRoute = TechStackTechIdRouteImport.update({
  id: '/tech-stack/$techId',
  path: '/tech-stack/$techId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceServiceIdRoute = ServiceServiceIdRouteImport.update({
  id: '/service/$serviceId',
  path: '/service/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioProjectIdRoute = PortfolioProjectIdRouteImport.update({
  id: '/portfolio/$projectId',
  path: '/portfolio/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBlogIdRoute = BlogBlogIdRouteImport.update({
  id: '/blog/$blogId',
  path: '/blog/$blogId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/kb': typeof KbRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/blog/$blogId': typeof BlogBlogIdRoute
  '/portfolio/$projectId': typeof PortfolioProjectIdRoute
  '/service/$serviceId': typeof ServiceServiceIdRoute
  '/tech-stack/$techId': typeof TechStackTechIdRoute
  '/blog/': typeof BlogIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/service/': typeof ServiceIndexRoute
  '/tech-stack/': typeof TechStackIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/kb': typeof KbRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/blog/$blogId': typeof BlogBlogIdRoute
  '/portfolio/$projectId': typeof PortfolioProjectIdRoute
  '/service/$serviceId': typeof ServiceServiceIdRoute
  '/tech-stack/$techId': typeof TechStackTechIdRoute
  '/blog': typeof BlogIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/service': typeof ServiceIndexRoute
  '/tech-stack': typeof TechStackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/kb': typeof KbRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/blog/$blogId': typeof BlogBlogIdRoute
  '/portfolio/$projectId': typeof PortfolioProjectIdRoute
  '/service/$serviceId': typeof ServiceServiceIdRoute
  '/tech-stack/$techId': typeof TechStackTechIdRoute
  '/blog/': typeof BlogIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/service/': typeof ServiceIndexRoute
  '/tech-stack/': typeof TechStackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/get-started'
    | '/kb'
    | '/privacy'
    | '/search'
    | '/support'
    | '/terms'
    | '/blog/$blogId'
    | '/portfolio/$projectId'
    | '/service/$serviceId'
    | '/tech-stack/$techId'
    | '/blog/'
    | '/portfolio/'
    | '/service/'
    | '/tech-stack/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/get-started'
    | '/kb'
    | '/privacy'
    | '/search'
    | '/support'
    | '/terms'
    | '/blog/$blogId'
    | '/portfolio/$projectId'
    | '/service/$serviceId'
    | '/tech-stack/$techId'
    | '/blog'
    | '/portfolio'
    | '/service'
    | '/tech-stack'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/get-started'
    | '/kb'
    | '/privacy'
    | '/search'
    | '/support'
    | '/terms'
    | '/blog/$blogId'
    | '/portfolio/$projectId'
    | '/service/$serviceId'
    | '/tech-stack/$techId'
    | '/blog/'
    | '/portfolio/'
    | '/service/'
    | '/tech-stack/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GetStartedRoute: typeof GetStartedRoute
  KbRoute: typeof KbRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  BlogBlogIdRoute: typeof BlogBlogIdRoute
  PortfolioProjectIdRoute: typeof PortfolioProjectIdRoute
  ServiceServiceIdRoute: typeof ServiceServiceIdRoute
  TechStackTechIdRoute: typeof TechStackTechIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  ServiceIndexRoute: typeof ServiceIndexRoute
  TechStackIndexRoute: typeof TechStackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kb': {
      id: '/kb'
      path: '/kb'
      fullPath: '/kb'
      preLoaderRoute: typeof KbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-stack/': {
      id: '/tech-stack/'
      path: '/tech-stack'
      fullPath: '/tech-stack/'
      preLoaderRoute: typeof TechStackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/': {
      id: '/service/'
      path: '/service'
      fullPath: '/service/'
      preLoaderRoute: typeof ServiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-stack/$techId': {
      id: '/tech-stack/$techId'
      path: '/tech-stack/$techId'
      fullPath: '/tech-stack/$techId'
      preLoaderRoute: typeof TechStackTechIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$serviceId': {
      id: '/service/$serviceId'
      path: '/service/$serviceId'
      fullPath: '/service/$serviceId'
      preLoaderRoute: typeof ServiceServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$projectId': {
      id: '/portfolio/$projectId'
      path: '/portfolio/$projectId'
      fullPath: '/portfolio/$projectId'
      preLoaderRoute: typeof PortfolioProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$blogId': {
      id: '/blog/$blogId'
      path: '/blog/$blogId'
      fullPath: '/blog/$blogId'
      preLoaderRoute: typeof BlogBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GetStartedRoute: GetStartedRoute,
  KbRoute: KbRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  BlogBlogIdRoute: BlogBlogIdRoute,
  PortfolioProjectIdRoute: PortfolioProjectIdRoute,
  ServiceServiceIdRoute: ServiceServiceIdRoute,
  TechStackTechIdRoute: TechStackTechIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  ServiceIndexRoute: ServiceIndexRoute,
  TechStackIndexRoute: TechStackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
